from collections.abc import Callable
from typing import Any

from fnutil.iterator import Iterator

class Expression[T]:
    def __init__(self, value: T) -> None: ...
    @property
    def value(self) -> T: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

    # Transform
    def map[U](self, fn: Callable[[T], U]) -> Expression[U]: ...
    def flat_map[U](
        self, fn: Callable[[T], Expression[U]]
    ) -> Expression[U]: ...
    def pipe(self, *fns: Callable) -> Expression: ...
    def then[U](self, fn: Callable[[T], U]) -> U: ...

    # Inspection
    def inspect(self, fn: Callable[[T], object]) -> Expression[T]: ...

    # Option-like
    @property
    def is_some(self) -> bool: ...
    @property
    def is_none(self) -> bool: ...
    def filter(self, fn: Callable[[T], bool]) -> Expression[T | None]: ...
    def or_else[U](self, default: U) -> Expression[T | U]: ...
    def or_else_with[U](self, fn: Callable[[], U]) -> Expression[T | U]: ...
    def unwrap_or[U](self, default: U) -> T | U: ...

    # Iterator interop
    def iter(self: Expression[Any]) -> Iterator[Any]: ...

    # Arithmetic operators
    def __add__(self, other: Expression[T]) -> Expression[T]: ...
    def __sub__(self, other: Expression[T]) -> Expression[T]: ...
    def __mul__(self, other: Expression[T]) -> Expression[T]: ...
    def __truediv__(self, other: Expression[T]) -> Expression[T]: ...
    def __floordiv__(self, other: Expression[T]) -> Expression[T]: ...
    def __mod__(self, other: Expression[T]) -> Expression[T]: ...
    def __pow__(self, other: Expression[T]) -> Expression[T]: ...
    def __neg__(self) -> Expression[T]: ...
    def __abs__(self) -> Expression[T]: ...

    # Comparison operators
    def __lt__(self, other: Expression[T]) -> bool: ...
    def __le__(self, other: Expression[T]) -> bool: ...
    def __gt__(self, other: Expression[T]) -> bool: ...
    def __ge__(self, other: Expression[T]) -> bool: ...

def expr[T](value: T) -> Expression[T]: ...
