from collections.abc import Callable, Iterable
from collections.abc import Iterator as BuiltinIterator
from typing import (
    Any,
    overload,
)

from fnutil.expression import Expression

def it[T](iterable: Iterable[T]) -> Iterator[T]: ...

class Iterator[T]:
    def __init__(self, iterable: Iterable[T]) -> None: ...
    def __iter__(self) -> BuiltinIterator[T]: ...
    @overload
    def __getitem__(self, index: int) -> Iterator[T]: ...
    @overload
    def __getitem__(self, index: slice) -> Iterator[T]: ...
    def __getitem__(self, index: int | slice) -> Iterator[T]: ...

    # Lazy adapters
    def filter(self, fn: Callable[[T], bool]) -> Iterator[T]: ...
    def map[U](self, fn: Callable[[T], U]) -> Iterator[U]: ...
    def enumerate(self) -> Iterator[tuple[int, T]]: ...
    def zip[U](self, other: Iterable[U]) -> Iterator[tuple[T, U]]: ...
    def chain(self, other: Iterable[T]) -> Iterator[T]: ...
    def take(self, n: int) -> Iterator[T]: ...
    def skip(self, n: int) -> Iterator[T]: ...
    def take_while(self, fn: Callable[[T], bool]) -> Iterator[T]: ...
    def skip_while(self, fn: Callable[[T], bool]) -> Iterator[T]: ...
    def flat_map[U](self, fn: Callable[[T], Iterable[U]]) -> Iterator[U]: ...
    def flatten(self: Iterator[Any]) -> Iterator[Any]: ...
    def inspect(self, fn: Callable[[T], None]) -> Iterator[T]: ...
    def filter_false(self, fn: Callable[[T], bool]) -> Iterator[T]: ...
    def accumulate(
        self,
        fn: Callable[[T, T], T] | None = ...,
        *,
        initial: T | None = ...,
    ) -> Iterator[T]: ...
    def cycle(self) -> Iterator[T]: ...
    def batched(self, n: int) -> Iterator[tuple[T, ...]]: ...
    def pairwise(self) -> Iterator[tuple[T, T]]: ...
    def compress(self, selectors: Iterable) -> Iterator[T]: ...
    def zip_longest[U](
        self,
        other: Iterable[U],
        fillvalue: T | U | None = ...,
    ) -> Iterator[tuple[T | None, U | None]]: ...
    def starmap[U](self, fn: Callable[..., U]) -> Iterator[U]: ...
    @overload
    def group_by(self, fn: None = ...) -> Iterator[tuple[T, Iterator[T]]]: ...
    @overload
    def group_by[K](
        self, fn: Callable[[T], K]
    ) -> Iterator[tuple[K, Iterator[T]]]: ...
    def group_by[K](
        self, fn: Callable[[T], K] | None = ...
    ) -> Iterator[tuple[K, Iterator[T]]]: ...

    # Consuming terminators
    def fold[U](self, init: U, fn: Callable[[U, T], U]) -> U: ...
    def reduce(self, fn: Callable[[T, T], T]) -> T | None: ...
    def for_each(self, fn: Callable[[T], None]) -> None: ...
    def count(self) -> int: ...
    def find(self, fn: Callable[[T], bool]) -> T | None: ...
    def any(self, fn: Callable[[T], bool]) -> bool: ...
    def all(self, fn: Callable[[T], bool]) -> bool: ...
    def min(self) -> T | None: ...
    def max(self) -> T | None: ...
    def nth(self, n: int) -> T | None: ...
    def last(self) -> T | None: ...
    def partition(
        self, fn: Callable[[T], bool]
    ) -> tuple[list[T], list[T]]: ...
    def collect[U](self, factory: Callable[[Iterable[T]], U]) -> U: ...
    def collect_expr[U](
        self, factory: Callable[[Iterable[T]], U]
    ) -> Expression[U]: ...
    @property
    def value(self) -> Iterable[T]: ...
